███╗   ██╗███████╗██╗  ██╗ ██████╗     ███╗   ███╗██████╗ 
████╗  ██║██╔════╝╚██╗██╔╝██╔═══██╗    ████╗ ████║██╔══██╗
██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║    ██╔████╔██║██║  ██║
██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║    ██║╚██╔╝██║██║  ██║
██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝    ██║ ╚═╝ ██║██████╔╝
╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝     ╚═╝     ╚═╝╚═════╝ 

══════════════════════════════════════════════════════════════════════════
                           ( OWNER DETAILS )
══════════════════════════════════════════════════════════════════════════
✅ NEXO MD Multi-device Whatsapp Bot
✅ Coded By SVOG 
══════════════════════════════════════════════════════════════════════════
                             ( CONTACT ME )
══════════════════════════════════════════════════════════════════════════
✅ Telegram: 727364174
✅ Whatsapp: 727364174
✅ Instagram:@gamingrexo 
✅ Youtube: @gaming_rexo                                                                                                      
══════════════════════════════════════════════════════════════════════════
                            ( PROJECT DETAILS )
══════════════════════════════════════════════════════════════════════════
✅ @project_name NEXO-MD [WA Multi-device]
✅ @author DarkWinzo <https://github.com/fdolarning-afk>
✅ @description A WhatsApp based 3ʳᵈ party application that provide many 
   services with a real-time automated conversational experience
✅ @link <https://github.com/fdolarning/nexobot>
✅ @version 0.0.1
══════════════════════════════════════════════════════════════════════════
                            ( PROJECT RULES )
══════════════════════════════════════════════════════════════════════════
✅ If you want to recode, reupload
   or copy the codes/script,
   please Contact me;
✅ If the recoded/reupload or copy script? "i will take action immediately"
✅ © 2025 NEXO Bot Inc. Technical Hacker Team
✅ God Bless You, Family and Myself
══════════════════════════════════════════════════════════════════════════
